spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/etc_management?characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai

    username: root
    password: root
    #   hikari数据源配置
    hikari:
        connection-test-query: SELECT 1 FROM DUAL
        connection-timeout: 30000
        maximum-pool-size: 20
        max-lifetime: 1800000
        minimum-idle: 5
server:
  port: 10010
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.internship.ds.model